### ISSUE TITLE
使用tidevices+wda+wdapy提示错误，未知命令

### ISSUE THREAD

**Issue by dmdada** [openatx/wdapy#3]
wdapy.exceptions.ApiError: ('unknown command', 'Unhandled endpoint: /wda/swipe -- http://localhost:8100/ with parameters {\n    wildcards =     (\n        "wda/swipe"\n    );\n}')

**Comment by codeskyblue** [comment]
这个取决于你用的WDA的维护者，appium下面的WDA应该没有这个路由，但是还有一个项目的版本 https://github.com/nanoscopic/WebDriverAgent 是有这个路由的

**Comment by dmdada** [comment]
我使用了新的接口可以滑动了速度也很快，想问问有没有滚动接口，我需要页面匀速滚动，目前看来滑动与滑动之间还是有停顿的

**Comment by codeskyblue** [comment]
新增加了一个这个接口

```python

from wdapy import Gesture, GestureOption as Option
c.touch_perform([
    Gesture("press", Option(x=100, y=200)),
    Gesture("wait", Option(ms=100)), # ms shoud > 17
    Gesture("moveTo", Option(x=100, y = 100)),
    Gesture("release")
])
```
